# Generated by Django 5.0.1 on 2024-01-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_prov', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
