# Generated by Django 5.0.1 on 2024-01-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['number']},
        ),
        migrations.AlterIndexTogether(
            name='team',
            index_together={('city', 'country'), ('city', 'state_prov', 'country'), ('state_prov', 'country')},
        ),
    ]
