# Generated by Django 5.0.1 on 2024-01-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_options_alter_team_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
