# Generated by Django 5.0.1 on 2024-01-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_prov', models.CharField(max_length=100)),
                ('country', models.CharField(default='Null', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='season.season')),
            ],
            options={
                'index_together': {('city', 'country'), ('city', 'state_prov', 'country'), ('state_prov', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('blue_alliance', models.ManyToManyField(related_name='blue_alliance', to='team.team')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='season.event')),
                ('red_alliance', models.ManyToManyField(related_name='red_alliance', to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'index_together': {('event', 'key')},
            },
        ),
    ]
