# Generated by Django 5.0.1 on 2024-01-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterIndexTogether(
            name='event',
            index_together={('city', 'country'), ('city', 'state_prov', 'country'), ('state_prov', 'country')},
        ),
        migrations.AlterIndexTogether(
            name='match',
            index_together={('event', 'key')},
        ),
    ]
