# Generated by Django 5.0.1 on 2024-01-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
