# Generated by Django 5.0.1 on 2024-01-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_alter_event_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='week',
            field=models.IntegerField(default=-1),
        ),
    ]
