# Generated by Django 5.0.1 on 2024-01-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0005_alter_event_week'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='event',
            index_together={('city', 'country'), ('city', 'state_prov', 'country'), ('city', 'state_prov', 'country', 'name'), ('state_prov', 'country')},
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(related_name='events', to='team.team'),
        ),
    ]
